version: '3.8'

volumes:
  data: {}

networks:
  default:
    name: mongodb_network

services:
  mongodb:
    image: "mongo"
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    volumes:
    - data:/data
    ports:
    - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

    # resume-builder:
    #   container_name: 'resume-builder'
    #   build:
    #     context: .
    #   ports:
    #     - '8080:8080'
    #   volumes:
    #     - /opt/server-img/:/server-img/
    #   depends_on:
    #     - resume-db


